In [14]:
import pandas as pd
import numpy as np

In [15]:
links = pd.read_csv('C:\\Users\\DELL\\Desktop\\ml-20m\\ml-20m\\links.csv')
links

       movieId   imdbId    tmdbId
0            1   114709     862.0
1            2   113497    8844.0
2            3   113228   15602.0
3            4   114885   31357.0
4            5   113041   11862.0
...        ...      ...       ...
27273   131254   466713    4436.0
27274   131256   277703    9274.0
27275   131258  3485166  285213.0
27276   131260   249110   32099.0
27277   131262  1724965  286971.0

[27278 rows x 3 columns]

In [16]:
movie = pd.read_csv('C:\\Users\\DELL\\Desktop\\ml-20m\\ml-20m\\movies.csv')
movie

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [17]:
ratings = pd.read_csv('C:\\Users\\DELL\\Desktop\\ml-20m\\ml-20m\\ratings.csv')
ratings

          userId  movieId  rating   timestamp
0              1        2     3.5  1112486027
1              1       29     3.5  1112484676
2              1       32     3.5  1112484819
3              1       47     3.5  1112484727
4              1       50     3.5  1112484580
...          ...      ...     ...         ...
20000258  138493    68954     4.5  1258126920
20000259  138493    69526     4.5  1259865108
20000260  138493    69644     3.0  1260209457
20000261  138493    70286     5.0  1258126944
20000262  138493    71619     2.5  1255811136

[20000263 rows x 4 columns]

In [18]:
ratings.drop('timestamp',axis=1,inplace=True)
ratings

          userId  movieId  rating
0              1        2     3.5
1              1       29     3.5
2              1       32     3.5
3              1       47     3.5
4              1       50     3.5
...          ...      ...     ...
20000258  138493    68954     4.5
20000259  138493    69526     4.5
20000260  138493    69644     3.0
20000261  138493    70286     5.0
20000262  138493    71619     2.5

[20000263 rows x 3 columns]

In [19]:
merge = pd.merge(ratings, movie, on = 'movieId')
merge

,userId,movieId,rating,title,genres
0,1,2,3.5,Jumanji (1995),Adventure|Children|Fantasy
1,5,2,3.0,Jumanji (1995),Adventure|Children|Fantasy
2,13,2,3.0,Jumanji (1995),Adventure|Children|Fantasy
3,29,2,3.0,Jumanji (1995),Adventure|Children|Fantasy
4,34,2,3.0,Jumanji (1995),Adventure|Children|Fantasy
...,...,...,...,...,...
20000258,138301,121017,3.5,The Gentleman from Epsom (1962),Comedy|Crime
20000259,138301,121019,4.5,The Great Spy Chase (1964),Action|Comedy|Thriller
20000260,138301,121021,4.5,Taxi for Tobruk (1961),Drama|War
20000261,138406,110167,4.5,"Judge and the Assassin, The (Juge et l'assassi...",Crime|Drama
20000262,138406,110510,4.5,Série noire (1979),Film-Noir

In [20]:
merge1 = pd.merge(merge, links, on = 'movieId')
merge1

,userId,movieId,rating,title,genres,imdbId,tmdbId
0,1,2,3.5,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
1,5,2,3.0,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
2,13,2,3.0,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
3,29,2,3.0,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
4,34,2,3.0,Jumanji (1995),Adventure|Children|Fantasy,113497,8844.0
...,...,...,...,...,...,...,...
20000258,138301,121017,3.5,The Gentleman from Epsom (1962),Comedy|Crime,56014,44522.0
20000259,138301,121019,4.5,The Great Spy Chase (1964),Action|Comedy|Thriller,57870,31270.0
20000260,138301,121021,4.5,Taxi for Tobruk (1961),Drama|War,54425,33336.0
20000261,138406,110167,4.5,"Judge and the Assassin, The (Juge et l'assassi...",Crime|Drama,73219,38080.0
20000262,138406,110510,4.5,Série noire (1979),Film-Noir,79980,64349.0

In [129]:
imdb = merge1.groupby('imdbId')['rating'].count().reset_index()
imdb

       imdbId  rating
0         417       1
1        2844       1
2        4972       2
3        6864       2
4        8133       1
...       ...     ...
9409  3165608       1
9410  3521134       1
9411  3762944       2
9412  3872778       1
9413  4044364       1

[9414 rows x 2 columns]

In [137]:
final.shape

(9414, 2)

In [138]:
final = merge1[merge1['rating'].isin(imdb.index)]
final

        userId  movieId  rating  ...                      genres  imdbId   tmdbId
1            5        2     3.0  ...  Adventure|Children|Fantasy  113497   8844.0
2           13        2     3.0  ...  Adventure|Children|Fantasy  113497   8844.0
3           29        2     3.0  ...  Adventure|Children|Fantasy  113497   8844.0
4           34        2     3.0  ...  Adventure|Children|Fantasy  113497   8844.0
5           54        2     3.0  ...  Adventure|Children|Fantasy  113497   8844.0
...        ...      ...     ...  ...                         ...     ...      ...
129023     868     7787     4.0  ...            Action|Drama|War   48729  16514.0
129025     872     7753     3.0  ...                       Drama  207805  26133.0
129027     872    44241     3.0  ...       Comedy|Fantasy|Horror  113636  19286.0
129028     872    62718     4.0  ...              Comedy|Romance  963743  12689.0
129030     873     6672     4.0  ...             Documentary|War  309061  12722.0

[96050 rows x 7 columns]

In [139]:
pivot=data.pivot_table(columns='imdbId',index='title',values='rating')
pivot

imdbId                            6864     9018     ...  3762944  4044364
title                                               ...
"Great Performances" Cats (1998)      NaN      NaN  ...      NaN      NaN
'Round Midnight (1986)                NaN      NaN  ...      NaN      NaN
'Salem's Lot (2004)                   NaN      NaN  ...      NaN      NaN
'Til There Was You (1997)             NaN      NaN  ...      NaN      NaN
'burbs, The (1989)                    NaN      NaN  ...      NaN      NaN
...                                   ...      ...  ...      ...      ...
[REC] (2007)                          NaN      NaN  ...      NaN      NaN
eXistenZ (1999)                       NaN      NaN  ...      NaN      NaN
xXx (2002)                            NaN      NaN  ...      NaN      NaN
xXx: State of the Union (2005)        NaN      NaN  ...      NaN      NaN
¡Three Amigos! (1986)                 NaN      NaN  ...      NaN      NaN

[8005 rows x 8007 columns]

In [140]:
pivot.fillna(0,inplace=True)
pivot

imdbId                            6864     9018     ...  3762944  4044364
title                                               ...
"Great Performances" Cats (1998)      0.0      0.0  ...      0.0      0.0
'Round Midnight (1986)                0.0      0.0  ...      0.0      0.0
'Salem's Lot (2004)                   0.0      0.0  ...      0.0      0.0
'Til There Was You (1997)             0.0      0.0  ...      0.0      0.0
'burbs, The (1989)                    0.0      0.0  ...      0.0      0.0
...                                   ...      ...  ...      ...      ...
[REC] (2007)                          0.0      0.0  ...      0.0      0.0
eXistenZ (1999)                       0.0      0.0  ...      0.0      0.0
xXx (2002)                            0.0      0.0  ...      0.0      0.0
xXx: State of the Union (2005)        0.0      0.0  ...      0.0      0.0
¡Three Amigos! (1986)                 0.0      0.0  ...      0.0      0.0

[8005 rows x 8007 columns]

In [141]:
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
movmatrix=csr_matrix(pivot)
model=NearestNeighbors(algorithm='brute')
model.fit(movmatrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                 radius=1.0)

In [142]:
pivot.index[500]

'At Close Range (1986)'

In [143]:
distance,suggestion=model.kneighbors(pivot.iloc[1,:].values.reshape(1,-1),n_neighbors=5)

In [144]:
suggestion

array([[   1, 5373, 5431, 5450, 1869]])

In [145]:
def recommend(moviename):
    im_id=np.where(pivot.index==moviename)[0][0]
    distance,suggestion=model.kneighbors(pivot.iloc[im_id,:].values.reshape(1,-1),n_neighbors=5)
    for i in suggestion[0]:
        print(pivot.index[i])

In [146]:
recommend('101 Dalmatians (1996)')

101 Dalmatians (1996)
Adventures of Elmo in Grouchland, The (1999)
Death Ship (1980)
Terror in a Texas Town (1958)
We're Back! A Dinosaur's Story (1993)

In [148]:
recommend('xXx (2002)')

xXx (2002)
Death Ship (1980)
Adventures of Elmo in Grouchland, The (1999)
Paris, France (1993)
Pathfinder (2007)

In [149]:
recommend('Sunless (Sans Soleil) (1983)')

Sunless (Sans Soleil) (1983)
We're Back! A Dinosaur's Story (1993)
Ashes of Time (Dung che sai duk) (1994)
Paris, France (1993)
Terror in a Texas Town (1958)

In [150]:
recommend('At Close Range (1986)')

At Close Range (1986)
We're Back! A Dinosaur's Story (1993)
Ashes of Time (Dung che sai duk) (1994)
Paris, France (1993)
Terror in a Texas Town (1958)